//CONFIG
export const CONNECT_TO_ETH_ACTION = 'CONNECT_TO_ETH_ACTION';
export const SET_CONFIG_DATA_ACTION = 'SET_CONFIG_DATA_ACTION';
export const DISCONNECT_ACTION = "DISCONNECT_ACTION";
export const ETH_DISCONNECTED = "ETH_DISCONNECTED";

//EVENTS
export const TOGGLE_EVENT = "TOGGLE_EVENT";
export const EVENT_LISTENER_STATUS_CHANGED_ACTION = "EVENT_LISTENER_STATUS_CHANGED_ACTION";
export const NEW_EVENT_ACTION = "NEW_EVENT_ACTION";

//TABS
export const SELECT_TAB = 'SELECT_TAB';